spring:
  datasource:
    url: jdbc:mysql://localhost:3306/port?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: "root"
    password: "020491"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/*.xml

server:
  port: 8001

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0

